
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace giadinhthoxinh.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblComment
{

    public int PK_iCommentID { get; set; }

    public int FK_iProductID { get; set; }

    public int FK_iAccountID { get; set; }

    public string sContent { get; set; }

    public System.DateTime dtCreateDate { get; set; }

    public bool bStatus { get; set; }



    public virtual tblProduct tblProduct { get; set; }

    public virtual tblUser tblUser { get; set; }

}

}
